- tests/fixture/columns.js
- tests/fixture/table.js
- tests/unit/components/ember-table-test.js
- tests/unit/components/partial-data-sort-test.js
- tests/unit/components/sort-indicator-test.js
- extract fixtures to remove duplicates in setting up a table.
> Refactor tests.

- Brocfile.js
- addon/components/ember-table.js
- addon/views/header-cell.js
- addon/views/header-groups-block.js
- app/templates/header-groups-block.hbs
- app/templates/header-table-container.hbs
- bower.json
- tests/fixture/columns.js
- tests/fixture/ember-table-with-group-and-fixed.js
- tests/fixture/ember-table.js
- tests/fixture/table.js
- tests/helpers/ember-table-helper.js
- tests/unit/components/ember-table-test.js
- vendor/simulate-drag-sortable.js
Make column group work with fixed column
> Column group and fixed

- tests/fixture/table.js
- tests/helpers/ember-table-helper.js
- tests/helpers/module-for-ember-table.js
- tests/unit/components/ember-table-test.js
- tests/unit/components/grouping-column-test.js
- tests/unit/components/partial-data-sort-test.js
- tests/unit/components/sort-indicator-test.js
- create moduleForEmberTable to avoid duplicate of needs
> reorder ember table test.

- addon/components/ember-table.js
- addon/controllers/grouped-row-array.js
- addon/controllers/row.js
- addon/views/grouping-column-cell.js
- app/templates/grouping-column-cell.hbs
- tests/helpers/ember-table-helper.js
- tests/helpers/module-for-ember-table.js
- tests/unit/components/grouping-column-test.js
- tests/unit/controllers/grouped-row-array-test.js
-add grouped row controller
-fix tests
> can expand/collapse one level group row

- addon/components/ember-table.js
- addon/controllers/grouped-row-array.js
- addon/views/grouping-column-cell.js
- tests/unit/components/grouping-column-test.js
Grouping column width will be recalculated when expand depth changes. 
` Grouping column width = default grouping column width + width of grouping indicator * expanded level`
> Grouping column auto expanding unlimited level

- addon/components/ember-table.js
- addon/controllers/row.js
- addon/views/grouped-row-indicator.js
- addon/views/grouping-column-cell.js
- app/templates/grouped-row-indicator.hbs
- app/templates/grouping-column-cell.hbs
- app/views/grouped-row-indicator.js
- tests/fixture/ember-table.js
- tests/helpers/ember-table-helper.js
- tests/helpers/module-for-ember-table.js
- tests/unit/components/grouping-column-test.js
- tests/unit/controllers/grouped-row-array-test.js
Move grouped row indicator to grouped-row-indicator view.
We can custom grouped row indicator view class.
> Merge conflact with refactor grouped row

- addon/styles/addon.less
- addon/views/row-loading-indicator.js
- app/templates/grouping-column-cell.hbs
- app/templates/row-loading-indicator.hbs
- app/views/row-loading-indicator.js
- tests/helpers/module-for-ember-table.js
- tests/unit/components/loading-indicator-test.js
Replace loading indicator by view/component
> Row loading indicator component

- addon/components/ember-table.js
- addon/views/grouped-row-indicator.js
- tests/fixture/ember-table.js
- tests/unit/components/chunked-grouping-row-test.js
- tests/unit/components/grouping-column-test.js
- tests/unit/components/loading-indicator-test.js
> Grouping column lable

- addon/components/ember-table.js
- addon/controllers/grouped-row-array.js
- addon/controllers/row.js
- addon/models/grand-total-row.js
- addon/models/grouping-row-proxy.js
- addon/views/grouping-column-cell.js
- tests/unit/components/grand-total-test.js
- can set grand total label
- grand total row is not included in grouping metadata
> Grand total row

- addon/components/ember-table.js
- addon/controllers/grouped-row-array.js
- addon/models/grouping-row-proxy.js
- addon/models/lazy-group-row-array.js
- addon/views/lazy-container.js
- app/templates/body-table-container.hbs
- tests/fixture/grouped-row-data-provider.js
- tests/helpers/ember-table-helper.js
- tests/unit/components/grouped-row-sort-test.js
1 Sorted grouped rows.
2 Fixed defect of loading extra chunk when expand again.
> Sorted grouped rows

- addon/styles/addon.less
- addon/views/grouped-row-indicator.js
- addon/views/grouping-column-cell.js
- tests/unit/components/ember-table-grouping-column-cell-test.js
- tests/unit/components/grouping-column-test.js
- make grouping row indicator absolute, cell content width 100%
> fixed grouping cell long text rendering into next row.

- tests/unit/components/chunked-grouping-row-test.js
This case cover the situation of loading indicator which only return only one 'row' data to ensure showing the data.
> Add grouped row special test case for lazy load indicator

- addon/styles/addon.less
- addon/views/header-group.js
- app/templates/body-table-container.hbs
- tests/helpers/ember-table-helper.js
- tests/unit/components/grouped-row-sort-test.js
1. Fixed defect of auto resize grouping column width
2. Refactored cell content assertion
> Fix defect of auto resize grouping column width

- addon/models/sorting-columns.js
- addon/styles/addon.less
- addon/views/column-sort-indicator.js
- addon/views/header-cell.js
- app/templates/column-sort-indicator.hbs
- app/templates/header-cell.hbs
- app/views/column-sort-indicator.js
- tests/helpers/ember-table-helper.js
- tests/helpers/module-for-ember-table.js
- tests/unit/components/sort-indicator-test.js
- Add findOrder function on 'sortingColumns' and binding sort order
- Edit column-sort-indicator css style
> Add column-sort-indicator view to wrap sort order and sort indicator

- addon/controllers/row.js
- addon/models/grand-total-row.js
- addon/models/grouped-array.js
- addon/models/grouping-row-proxy.js
- addon/models/grouping.js
- addon/models/lazy-array.js
- addon/models/lazy-group-row-array.js
- addon/models/loading-place-holder.js
- addon/models/sorting-columns.js
- addon/models/table-content.js
- tests/fixture/grouped-row-data-provider.js
- tests/unit/models/grouping-test.js
- extracted Grouping
- moved sort function to sorting columns
> Refactor grouping and sort functions.

- addon/components/ember-table.js
- addon/controllers/group-row.js
- addon/controllers/grouped-row-array.js
- addon/models/lazy-group-row-array.js
- tests/fixture/ember-table-with-gl-data.js
- tests/fixture/ember-table.js
- tests/fixture/grouped-row-data-provider.js
- tests/unit/components/chunked-grouping-row-test.js
- tests/unit/components/data-sort-test.js
- tests/unit/components/ember-table-grouping-column-cell-test.js
- tests/unit/components/ember-table-last-grouping-label-test.js
- tests/unit/components/grand-total-test.js
- tests/unit/components/grouped-row-sort-test.js
- tests/unit/components/grouping-column-test.js
- tests/unit/components/loading-indicator-test.js
- tests/unit/controllers/grouped-row-array-test.js
Created groupMeta, which includes all information needed for group rows. Specific group model is decided in ember-table.
> Hide lazy group model

- addon/controllers/group-row.js
- addon/controllers/grouped-row-array.js
- addon/controllers/sub-row-array.js
- addon/models/grouping.js
- tests/fixture/ember-table.js
- tests/unit/components/data-sort-test.js
- tests/unit/components/loading-indicator-test.js
- tests/unit/controllers/sub-row-array-test.js
Normal js array as ember content.
1. Sorted by grouper.
2. Sorted grouping rows when sort by column.
> Sort by grouper complete data

- addon/controllers/group-row.js
- addon/models/grouping.js
- tests/fixture/grouped-row-data-provider.js
- tests/helpers/table-dom.js
- tests/unit/components/data-sort-test.js
- tests/unit/components/grouped-row-sort-test.js
- tests/unit/models/grouping-test.js
1. Normal js array as ember table content and  sorted by groupers and columns.
2. Sort lazily loaded data by groupers.
> Sort lazily loaded data by groupers

- addon/components/ember-table.js
Replaced numFixedColumns by _numFixedColumns in ember table
> fix fixed columns count

- addon/models/column-definition.js
- addon/models/column-group-definition.js
- tests/unit/models/column-group-definition-test.js
- Change inner column styles when property on column group changed
- Return empty string instead of  `undefined` if no style
> Apply inner column styles in runtime.

- addon/components/ember-table.js
- addon/views/column-sort-indicator.js
- addon/views/grouping-column-cell.js
- addon/views/header-cell.js
- addon/views/table-cell.js
- app/templates/header-cell.hbs
Make following indicators changeable in runtime
- Group row indicator
- Row loading indicator
- Sort indicator
> Customize indicators

- addon/components/ember-table.js
- addon/controllers/group-row.js
- addon/controllers/grouped-row-array.js
- addon/views/grouping-column-cell.js
- tests/unit/components/grouping-column-test.js
- tests/unit/controllers/group-row-test.js
- tests/unit/controllers/grouped-row-array-test.js
1.  Recover grouping column resizable.
2.  Disable auto expaneding width.
> recover grouping column resizable and disable auto expaneded width

- tests/.jshintrc
- tests/fixture/defer-promises.js
- tests/fixture/ember-table.js
- tests/unit/components/expand-to-arbitrary-level-test.js
- Integrate table dom methods into ember table fixture
- Refactor defer promise to remove index and count
> Refactor ember table fixture

- addon/controllers/group-row.js
- addon/views/grouping-column-cell.js
- Allow empty row but can't expand/collapse it.
> Add group row control flags.

- addon/controllers/group-row.js
- addon/controllers/grouped-row-array.js
- addon/models/grouping.js
- tests/unit/controllers/group-row-test.js
Fixed tests:
- Control total row with no grouper
- Demo app WebDriver tests
> Fix tests.

- addon/controllers/grouped-row-array.js
- tests/unit/controllers/group-row-test.js
- grouping.isGroup is required for a valid group row.
> Fix group row test.

- addon/controllers/group-row.js
- addon/controllers/grouped-row-array.js
- addon/controllers/sub-row-array.js
- addon/models/lazy-group-row-array.js
- addon/views/lazy-container.js
- tests/helpers/table-dom.js
Group row used observer to calculate sub rows count. This PR uses computed property.
> Refactor group row chain

- addon/controllers/group-row.js
This was a try to fix [issue #154](https://github.com/hedgeserv/ember-table/issues/154).
> Try to ensure find row skip collapsed row.

- addon/models/column-definition.js
- addon/views/footer-block.js
- addon/views/footer-row.js
- addon/views/footer-table-container.js
- app/templates/footer-row.hbs
- app/templates/footer-table-container.hbs
- app/views/footer-block.js
- app/views/footer-row.js
- Based on @Gaurav0 's commit
- Fixed footer top value for column groups scenario(table has two rows of header)
- Fixed number of fixed columns for grouping column scenario(table has a grouping column, _ numFixedColumns = numFixedColumns + 1, you will need this if you have fixed grouping cells in footer rows)
> Customize footer
